replicaCount: 1
image:
  repository: docker-registry.127.0.0.1.nip.io:30500/sample-daemon
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
readinessProbe:
  exec:
    command:
    - cat
    - /data/bot.sh
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 6
livenessProbe:
  exec:
    command:
    - cat
    - /data/bot.sh
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 6
ingress:
  enabled: false
hpa:
  enabled: false
profile: default
